GH_PROXY=https://mirror.ghproxy.com/https://github.com
# 官方基础源 master（SDK全分支通用）
src-git packages ${GH_PROXY}/openwrt/packages.git;master
src-git luci ${GH_PROXY}/openwrt/luci.git;master
src-git routing ${GH_PROXY}/openwrt/routing.git;master

# 你的第三方插件库（全固件通用）
src-git small ${GH_PROXY}/Architect111/openwrt-packages.git
src-git smallpkg ${GH_PROXY}/Architect111/small-package.git
# 指定仓库内二级目录luci-app-quickfile-go，解决双层嵌套识别不到的问题
src-git mypkg ${GH_PROXY}/Architect111/my_personal_packages.git srcpath=luci-app-quickfile-go
