name: SDK-OpenWrt2410 轻量化编译插件
on:
  workflow_dispatch:
    inputs:
      pkg_list:
        description: 待编译插件，多包空格分隔
        required: true
        default: luci-app-vnt luci-app-quickfile-go luci-theme-argon luci-app-quickstart
      target_arch:
        description: 目标架构 aarch64_cortex-a53 / x86_64
        required: true
        default: aarch64_cortex-a53
      tag:
        description: Release标签，留空仅存产物不发布
        required: false
        default: ''
      release_text:
        description: Release自定义备注
        required: false
        default: OpenWrt 24.10 SDK 离线安装包

env:
  TZ: Asia/Shanghai
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码（读取根目录feeds.conf）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OpenWrt 24.10 SDK一键编译
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ github.event.inputs.target_arch }}-openwrt-24.10
          FEEDNAME: my_custom_pkg
          PACKAGES: ${{ github.event.inputs.pkg_list }}
          FEEDS_CONF: feeds.conf
          NO_REFRESH_CHECK: true
          V: s

      - name: 上传产物至Artifacts（永久留存）
        uses: actions/upload-artifact@v4
        with:
          name: SDK-OpenWrt2410-${{ github.event.inputs.target_arch }}
          path: bin/packages/${{ github.event.inputs.target_arch }}/my_custom_pkg/

      - name: 打包压缩包
        run: |
          ARCH=${{ github.event.inputs.target_arch }}
          zip -j OpenWrt2410_SDK_${ARCH}_$(date '+%Y%m%d-%H%M%S').zip bin/packages/${ARCH}/my_custom_pkg/*
          echo "build_time=$(date '+%Y年%m月%d日 %H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV

      - name: 发布Release（仅填写tag才执行）
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag }}
          name: OpenWrt 24.10 SDK编译包 ${{ env.build_time }}
          body: |
             > ### 
             - 固件类型：官方 OpenWrt 24.10
             - 目标架构：${{ github.event.inputs.target_arch }}
             - 编译插件：`${{ github.event.inputs.pkg_list }}`
             #### 前置依赖
             luci luci-base luci-compat kmod-tun
             #### IPK安装
             opkg install *.ipk
             #### APK新版安装
             apk add --allow-untrusted *.apk
             ${{ github.event.inputs.release_text }}
          files: OpenWrt2410_SDK_*.zip
          append_body: true
